### ISSUE TITLE
live switching of themes

### ISSUE THREAD

**Issue by realsnick** [librephoenix/nixos-config#3]
Hi, 

thanks for sharing your config! 

I'm wondering as briefly looking at your flake.nix you have the theme name hardcoded, by live switching a theme do you mean rebuilding a revision of nixos or you have a key-binding that will do that? I am not aware that stylix is even capable of that... 

Best,

Ido

**Comment by librephoenix** [comment]
Thanks!

The live switching I showcased does rebuild my home-manager and nixos.  The rebuilding goes pretty quick if you have the resultant system theme cached (meaning you switched into that theme previously without running nixos-collect-garbage).

For some apps (terminals, window managers), they reload automatically to switch the theme.  Unfortunately, for some other apps the themes don't reload nicely upon a rebuild (like already open gtk or qt apps).  Some apps don't live switch by default (like Emacs) but you can make workarounds (you could probably find some examples somewhere in [this mess](https://github.com/librephoenix/nixos-config/blob/main/user/bin/phoenix.nix), which is my "phoenix" wrapper script, which wraps around some of the rebuild commands).

Perhaps someday in the future stylix will get more support for live switching the theme!
