### ISSUE TITLE
Explanation on how the "auto" installation works

### ISSUE THREAD

**Issue by obvionaoe** [librephoenix/nixos-config#5]
Hi, I've been following your Nix videos as they are by far the best with regards to explaining Nix on YouTube.
The last video you posted got me really intrigued as the thing that has made me hold back from committing to NixOS fully, is an easy and fast way to bootstrap any new machine from my existing config.

I've figured the `apps` and `packages` attributes in the outputs generate some configuration for each of the systems inside the `supportedSystems` array. The `nix run` command uses those to decide what it should run. That's really clever.

I'd love if you could explain this process a bit and some of the Nix functions you've used, to achieve it, in a video. I've mostly figured out their use, but I think a video like that might be useful for other people as well.

Thanks

**Comment by obvionaoe** [comment]
Also, could you maybe explain the \@pattern? The docs explain it, but I still do not fully understand it

**Comment by librephoenix** [comment]
Definitely!  I'll be talking about those things in future videos.  My next video (currently working on it) will actually be on how I got the auto install script to work, since I had a lot of fun figuring out how to run apps/scripts directly from git via Nix :)

**Comment by obvionaoe** [comment]
Thanks so much!
