### ISSUE TITLE
`nix run home-manager switch` failed due to existing files in `~/.config/`

### ISSUE THREAD

**Issue by kohane27** [librephoenix/nixos-config#7]
Hello! It's me again.

I'm following [Manual Install Procedure](https://github.com/librephoenix/nixos-config/blob/main/install.org#manual-install-procedure) and the following command fails:

```bash
nix run home-manager/master -- switch --flake ~/.dotfiles#user
```

The error is below:

```
Existing file '/home/user/.gtkrc-2.0' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.gtkrc-2.0'
Existing file '/home/user/.config/Trolltech.conf' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/Trolltech.conf'
Existing file '/home/user/.config/user-dirs.conf' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/user-dirs.conf'
Existing file '/home/user/.config/user-dirs.dirs' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/user-dirs.dirs'
Existing file '/home/user/.config/gtk-4.0/gtk.css' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/gtk-4.0/gtk.css'
Existing file '/home/user/.config/gtk-4.0/settings.ini' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/gtk-4.0/settings.ini'
Existing file '/home/user/.config/kdeglobals' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/kdeglobals'
Existing file '/home/user/.config/gtk-3.0/gtk.css' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/gtk-3.0/gtk.css'
Existing file '/home/user/.config/gtk-3.0/settings.ini' is in the way of '/nix/store/6p3hzdbzhad8ra5j1qf4b2b3hs6as6sf-home-manager-files/.config/gtk-3.0/settings.ini'
Please move the above files and try again or use 'home-manager switch -b backup' to back up existing files automatically.
```

The solution was simple: just remove the files and run the command again.

I installed KDE from `nixos-plasma5-23.11.4976.79baff8812a0-x86_64-linux.iso`. Not sure if it would also happen if I installed Gnome instead.

During my first few attempted installs, I used the auto install script and didn't notice the above error (or they never showed up? I don't remember). After reboot, it booted into `hyprland` but it was a partial install. The wallpaper is the default wallpaper and it has the hyprland auto config warning. `Super+q` doesn't launch the terminal (because home-manager were never successfully installed and run). Booting into TTY confirmed that `alacritty` was not installed. It was a pretty frustrating experience. I'm not sure how this could be handled gracefully besides just adding a `rm -f ~/.config/path/to/above/files` in the auto install script. But I'm reporting this anyway in the hope that it's useful.

Thank you again! I successfully installed this configuration of yours and happily tinkering! Have a good day!

**Comment by librephoenix** [comment]
This is very helpful feedback!  I've been running all my tests in a minimal (tty) NixOS VM and didn't think about what would happen on the KDE or Gnome versions.

My inclination is probably that for now, this should probably be added as an FAQ thing rather than deleting config files via the script.  Though, maybe in the future I could add some non-default flag like --nuke-current-config to automate that.

**Comment by librephoenix** [comment]
Blurb added to FAQ ([004ff7f](https://github.com/librephoenix/nixos-config/commit/004ff7fa716c3cce34e546c3d8358060ce315ebf))

**Comment by kohane27** [comment]
Thank you for addressing this issue and adding it to the FAQ. Much appreciated!:)

**Comment by reinux** [comment]
I keep having to delete .gtkrc-2.0 and .config/fcitx5/profile . These two things have always kind of misbehaved, and I don't know how to get the programs to stop generating them all the time.

Any ideas?

**Comment by GreyStinger** [comment]
Found this issue while searching for a solution myself. This works for me; Home Manager has the following: [Appendix A. Home Manager Configuration Options](https://nix-community.github.io/home-manager/options.xhtml#opt-home.file._name_.force)

Which means we can do something like:
```nix
  home.file.".gtkrc-2.0".force = true;
```
